import type { Metadata } from "next";
import { Cormorant_Upright, Open_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header"
import Footer from "@/components/Footer"

const cormorantUpright = Cormorant_Upright({ 
  subsets: ["latin"]
  ,weight: ["300", "400", "500", "600", "700"] 
  ,variable: "--font-cormorant_upright"
});

const openSans = Open_Sans({ 
  subsets: ["latin"]
  ,weight: ["300", "400", "500", "600", "700", "800"] 
  ,variable: "--font-open_sans"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${cormorantUpright.variable} ${openSans.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
